name: CI-CD

on:
  push:
    branches: [ "main", "dev", "test/ci-cd" ]
  pull_request:
    branches: [ "main", "dev", "test/ci-cd" ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x']
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/upload-pages-artifact@v3
        with:
          name: artifact
          path: ./
      - name: Install Packages
        run: npm install
      - name: Build page
        run: npm run build
      - name: Copy Build Dir
        run: cp -a dist/. ./
      - name: Print working directory
        run: pwd
      - name: List All files
        run: ls -al
     
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          aws s3 --endpoint-url=https://kr.object.ncloudstorage.com cp --recursive ./ s3://rentit-bucket
